name: CI_kind
on:
  - push
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start kind
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.17.0"
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Deploy to kind
      run:
        kubectl apply -f deployment.yaml 
    - name: Required info
      run: |
         echo -e "\n$(kubectl get node)" 
         echo -e "\n$(kubectl version --short)\n" 
